sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm test && npm run coverage
after_success:
  - npm install -g travis-deploy-once semantic-release
  - travis-deploy-once "npm run semantic-release"
  - npm run coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/